export const QUESTION_SETS_ACTION_TYPES = {
  FETCH_QUESTION_SETS_REQUEST: 'questionSets/FETCH_QUESTION_SETS_REQUEST',
  FETCH_SET_QUESTIONS_REQUEST: 'questionSets/FETCH_SET_QUESTIONS_REQUEST',
  CREATE_QUESTION_SET_REQUEST: 'questionSets/CREATE_QUESTION_SET_REQUEST',
  CREATE_SCREEN_QUESTION_REQUEST: 'questionSets/CREATE_SCREEN_QUESTION_REQUEST',
  DELETE_SCREEN_QUESTION_REQUEST: 'questionSets/DELETE_SCREEN_QUESTION_REQUEST',
} as const;
