export const PROFILE_ACTION_TYPES = {
  GET_PROFILE_REQUEST: 'profile/GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'profile/GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'profile/GET_PROFILE_FAILURE',
  UPDATE_PROFILE_REQUEST: 'profile/UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'profile/UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'profile/UPDATE_PROFILE_FAILURE',
  CLEAR_ERROR: 'profile/CLEAR_ERROR',
} as const;

