export const RAPIDHIRE_ACTION_TYPES = {
  GET_CANDIDATES_REQUEST: 'rapidhire/GET_CANDIDATES_REQUEST',
  GET_CANDIDATES_SUCCESS: 'rapidhire/GET_CANDIDATES_SUCCESS',
  GET_CANDIDATES_FAILURE: 'rapidhire/GET_CANDIDATES_FAILURE',
  RESET_CANDIDATES: 'rapidhire/RESET_CANDIDATES',

  GET_INTERVIEW_REPORT_REQUEST: 'rapidhire/GET_INTERVIEW_REPORT_REQUEST',
  GET_INTERVIEW_REPORT_SUCCESS: 'rapidhire/GET_INTERVIEW_REPORT_SUCCESS',
  GET_INTERVIEW_REPORT_FAILURE: 'rapidhire/GET_INTERVIEW_REPORT_FAILURE',
  RESET_INTERVIEW_REPORT: 'rapidhire/RESET_INTERVIEW_REPORT',

  SEND_INTERVIEW_LINK_REQUEST: 'rapidhire/SEND_INTERVIEW_LINK_REQUEST',
  SEND_INTERVIEW_LINK_SUCCESS: 'rapidhire/SEND_INTERVIEW_LINK_SUCCESS',
  SEND_INTERVIEW_LINK_FAILURE: 'rapidhire/SEND_INTERVIEW_LINK_FAILURE',
} as const;
