export const USERS_ACTION_TYPES = {
  GET_USERS_REQUEST: "users/GET_USERS_REQUEST",
  GET_INVITES_REQUEST: "users/GET_INVITES_REQUEST",
  FETCH_DIRECTORY_USERS_LIST_REQUEST: "users/FETCH_DIRECTORY_USERS_LIST_REQUEST",
  GET_ROLES_REQUEST: "users/GET_ROLES_REQUEST",
  UPDATE_USER_REQUEST: "users/UPDATE_USER_REQUEST",
  CREATE_USER_REQUEST: "users/CREATE_USER_REQUEST",
  DELETE_USER_REQUEST: "users/DELETE_USER_REQUEST",
  INVITE_RESEND_REQUEST: "users/INVITE_RESEND_REQUEST",
  INVITE_REVOKE_REQUEST: "users/INVITE_REVOKE_REQUEST",
} as const;

