export const USERS_ACTION_TYPES = {
  GET_USERS_REQUEST: "users/GET_USERS_REQUEST",
  GET_ROLES_REQUEST: "users/GET_ROLES_REQUEST",
  UPDATE_USER_REQUEST: "users/UPDATE_USER_REQUEST",
  CREATE_USER_REQUEST: "users/CREATE_USER_REQUEST",
  DELETE_USER_REQUEST: "users/DELETE_USER_REQUEST",
} as const;

