export const ANALYTICS_ACTION_TYPES = {
  GET_ANALYTICS_REQUEST: "analytics/GET_ANALYTICS_REQUEST",
  GET_ANALYTICS_SUCCESS: "analytics/GET_ANALYTICS_SUCCESS",
  GET_ANALYTICS_FAILURE: "analytics/GET_ANALYTICS_FAILURE",
  CLEAR_ANALYTICS: "analytics/CLEAR_ANALYTICS",

  GET_STAGE_GRAPH_REQUEST: "analytics/GET_STAGE_GRAPH_REQUEST",
  GET_STAGE_GRAPH_SUCCESS: "analytics/GET_STAGE_GRAPH_SUCCESS",
  GET_STAGE_GRAPH_FAILURE: "analytics/GET_STAGE_GRAPH_FAILURE",

  GET_FEATURE_CONSUMPTION_REQUEST: "analytics/GET_FEATURE_CONSUMPTION_REQUEST",
  GET_FEATURE_CONSUMPTION_SUCCESS: "analytics/GET_FEATURE_CONSUMPTION_SUCCESS",
  GET_FEATURE_CONSUMPTION_FAILURE: "analytics/GET_FEATURE_CONSUMPTION_FAILURE",

  GET_WEEKLY_GRAPH_REQUEST: "analytics/GET_WEEKLY_GRAPH_REQUEST",
  GET_WEEKLY_GRAPH_SUCCESS: "analytics/GET_WEEKLY_GRAPH_SUCCESS",
  GET_WEEKLY_GRAPH_FAILURE: "analytics/GET_WEEKLY_GRAPH_FAILURE",

  GET_STAGE_GRAPH_OVERVIEW_REQUEST: "analytics/GET_STAGE_GRAPH_OVERVIEW_REQUEST",
  GET_STAGE_GRAPH_OVERVIEW_SUCCESS: "analytics/GET_STAGE_GRAPH_OVERVIEW_SUCCESS",
  GET_STAGE_GRAPH_OVERVIEW_FAILURE: "analytics/GET_STAGE_GRAPH_OVERVIEW_FAILURE",


} as const;
