import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    modalContent: {
      flex: 1,
      backgroundColor: "#000",
    },
    safeAreaContainer: {
      flex: 1,
      backgroundColor: "#000",
      justifyContent: "center",
      alignItems: "center",
    },
    fullscreenWrapper: {
      flex: 1,
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    container: {
      width: "100%",
      aspectRatio: 16 / 9,
      borderRadius: 14,
      overflow: "hidden",
      backgroundColor: "#000",
      alignSelf: "center",
    },
    fullscreen: {
      flex: 1,
      width: "100%",
      height: "100%",
      borderRadius: 0,
      aspectRatio: undefined,
      alignSelf: "stretch",
    },
    video: {
      width: "100%",
      height: "100%",
    },
    videoFullscreen: {
      width: "100%",
      height: "100%",
    },
    noVideoBox: {
      width: "100%",
      height: "100%",
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    noVideoText: {
      color: "#444",
      fontSize: 14,
      textAlign: "center",
    },
    bigPlayButton: {
      position: "absolute",
      alignSelf: "center",
      top: "40%",
    },
    loader: {
      position: "absolute",
      top: "45%",
      left: "45%",
    },
    controls: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      width: "100%",
      paddingHorizontal: 12,
      paddingVertical: 4,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 1000,
      elevation: 5,
      gap: 4,
    },
    controlsFullscreen: {
      left: 0,
      right: 0,
      bottom: 0,
      width: "100%",
      paddingHorizontal: 20,
      paddingVertical: 8,
      backgroundColor: "rgba(0,0,0,0.7)",
      marginHorizontal: 0,
      gap: 8,
    },
    controlButton: {
      padding: 4,
    },
    slider: {
      flex: 1,
      marginHorizontal: 8,
      height: 36,
      justifyContent: "center",
      position: "relative",
    },
    trackBackground: {
      height: 4,
      borderRadius: 2,
      backgroundColor: "#555555",
      width: "100%",
    },
    trackProgress: {
      position: "absolute",
      left: 0,
      height: 4,
      borderRadius: 2,
      backgroundColor: "#FFFFFF",
    },
    chapterDotTouchArea: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: 24,
      marginLeft: -12,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 5,
    },
    chapterDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: "#E5E7EB",
      borderWidth: 1,
      borderColor: "#1F2937",
    },
    chapterDotPassed: {
      backgroundColor: "#1F2937",
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    thumb: {
      position: "absolute",
      top: "50%",
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: "#FFFFFF",
      marginTop: -7,
      marginLeft: -7,
      zIndex: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.35,
      shadowRadius: 2,
      elevation: 3,
    },
    timeText: {
      color: "#fff",
      fontSize: 12,
      marginHorizontal: 4,
      textAlign: "left",
    },
    timeTextFullscreen: {
      fontSize: 14,
      marginHorizontal: 8,
    },
  });