import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    modalContent: {
      flex: 1,
      backgroundColor: "#000",
    },
    safeAreaContainer: {
      flex: 1,
      backgroundColor: "#000",
      justifyContent: "center",
      alignItems: "center",
    },
    fullscreenWrapper: {
      flex: 1,
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    container: {
      width: "100%",
      aspectRatio: 16 / 9,
      borderRadius: 14,
      overflow: "hidden",
      backgroundColor: "#000",
      alignSelf: "center",
    },
    fullscreen: {
      flex: 1,
      width: "100%",
      height: "100%",
      borderRadius: 0,
      aspectRatio: undefined,
      alignSelf: "stretch",
    },
    video: {
      width: "100%",
      height: "100%",
    },
    videoFullscreen: {
      width: "100%",
      height: "100%",
    },
    noVideoBox: {
      width: "100%",
      height: "100%",
      backgroundColor: "#fff",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    noVideoText: {
      color: "#444",
      fontSize: 14,
      textAlign: "center",
    },
    bigPlayButton: {
      position: "absolute",
      alignSelf: "center",
      top: "40%",
    },
    loader: {
      position: "absolute",
      top: "45%",
      left: "45%",
    },
    controls: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      width: "100%",
      paddingHorizontal: 12,
      paddingVertical: 4,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 1000,
      elevation: 5,
      gap: 4,
    },
    controlsFullscreen: {
      left: 0,
      right: 0,
      bottom: 0,
      width: "100%",
      paddingHorizontal: 20,
      paddingVertical: 8,
      backgroundColor: "rgba(0,0,0,0.7)",
      marginHorizontal: 0,
      gap: 8,
    },
    controlButton: {
      //padding: 4,
    },
    slider: {
      flex: 1,
      marginHorizontal: 4,
      height: 36,
    },
    timeText: {
      color: "#fff",
      fontSize: 12,
      marginHorizontal: 4,
      textAlign: "left",
    },
    timeTextFullscreen: {
      fontSize: 14,
      marginHorizontal: 8,
    },
  });