export const APPLICATIONS_ACTION_TYPES = {
  GET_APPLICATIONS_REQUEST: 'applications/GET_APPLICATIONS_REQUEST',
  GET_APPLICATIONS_SUCCESS: 'applications/GET_APPLICATIONS_SUCCESS',
  GET_APPLICATIONS_FAILURE: 'applications/GET_APPLICATIONS_FAILURE',
  GET_APPLICATION_DETAIL_REQUEST: 'applications/GET_APPLICATION_DETAIL_REQUEST',
  GET_APPLICATION_DETAIL_SUCCESS: 'applications/GET_APPLICATION_DETAIL_SUCCESS',
  GET_APPLICATION_DETAIL_FAILURE: 'applications/GET_APPLICATION_DETAIL_FAILURE',
  CREATE_APPLICATION_REQUEST: 'applications/CREATE_APPLICATION_REQUEST',
  CREATE_APPLICATION_SUCCESS: 'applications/CREATE_APPLICATION_SUCCESS',
  CREATE_APPLICATION_FAILURE: 'applications/CREATE_APPLICATION_FAILURE',
  UPDATE_APPLICATION_STATUS_REQUEST: 'applications/UPDATE_APPLICATION_STATUS_REQUEST',
  UPDATE_APPLICATION_STATUS_SUCCESS: 'applications/UPDATE_APPLICATION_STATUS_SUCCESS',
  UPDATE_APPLICATION_STATUS_FAILURE: 'applications/UPDATE_APPLICATION_STATUS_FAILURE',
  CLEAR_ERROR: 'applications/CLEAR_ERROR',
  SET_SELECTED_APPLICATION: 'applications/SET_SELECTED_APPLICATION',
} as const;

