export const AUTH_ACTION_TYPES = {
  LOGIN_REQUEST: 'auth/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'auth/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'auth/LOGIN_FAILURE',
  LOGOUT_REQUEST: 'auth/LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'auth/LOGOUT_SUCCESS',
  REGISTER_REQUEST: 'auth/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'auth/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'auth/REGISTER_FAILURE',
  REFRESH_TOKEN_REQUEST: 'auth/REFRESH_TOKEN_REQUEST',
  REFRESH_TOKEN_SUCCESS: 'auth/REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'auth/REFRESH_TOKEN_FAILURE',
  CLEAR_ERROR: 'auth/CLEAR_ERROR',
  // Legacy action type for backward compatibility
  ADD_USER: 'auth/ADD_USER',
  FORGOT_PASSWORD_REQUEST: "auth/FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "auth/FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "auth/FORGOT_PASSWORD_FAILURE",
  RESET_PASSWORD_REQUEST: "auth/RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "auth/RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "auth/RESET_PASSWORD_FAILURE",
} as const;

