import { StyleSheet } from 'react-native';
import { colors } from '../../../../../theme/colors';

export const useStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    rapidlyWrapper: {
      paddingBottom: 24,
    },
    rapidlyTopHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    rapidlyVideoContainer: {
      width: '100%',
      aspectRatio: 16 / 9,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: '#000',
      marginBottom: 16,
    },
    rapidlyVideo: {
      width: '100%',
      height: '100%',
    },
    rapidlyVideoFullscreen: {
      flex: 1,
      width: '100%',
      height: '100%',
      borderRadius: 0,
      aspectRatio: undefined,
    },
    rapidlyVideoFullscreenElement: {
      width: '100%',
      height: '100%',
    },
    rapidlyFullscreenSafeArea: {
      flex: 1,
      backgroundColor: '#000',
    },
    rapidlyLoader: {
      position: 'absolute',
      top: '45%',
      left: '45%',
    },
    rapidlyBigPlayButton: {
      position: 'absolute',
      alignSelf: 'center',
      top: '38%',
    },
    rapidlyControlBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      gap: 6,
    },
    rapidlyControlButton: {
      padding: 4,
    },
    rapidlyTimeText: {
      fontVariant: ['tabular-nums'],
    },
    rapidlyTimelineTrackWrapper: {
      flex: 1,
      height: 30,
      justifyContent: 'center',
      marginHorizontal: 4,
    },
    rapidlyTimelineTrack: {
      height: 4,
      backgroundColor: '#374151',
      borderRadius: 2,
      position: 'relative',
    },
    rapidlyTimelineProgress: {
      height: '100%',
      backgroundColor: colors.brand[500],
      borderRadius: 2,
    },
    rapidlyScrubberThumb: {
      position: 'absolute',
      top: -4,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.base.white,
      marginLeft: -6,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
    },
    rapidlyChapterMarker: {
      position: 'absolute',
      top: -2,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#9CA3AF',
      marginLeft: -4,
      borderWidth: 1,
      borderColor: '#1F2937',
    },
    rapidlyChapterMarkerPassed: {
      backgroundColor: colors.brand[200],
    },
    rapidlyCardContainer: {
      backgroundColor: colors.base.white,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    rapidlyQuestionCard: {
      backgroundColor: colors.base.white,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    rapidlyCardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    rapidlyHeaderRightWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    rapidlyStepperWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    rapidlyStepperBtn: {
      width: 32,
      height: 32,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.gray[300],
      backgroundColor: colors.base.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rapidlyStepperBtnDisabled: {
      borderColor: colors.gray[200],
      backgroundColor: colors.gray[50],
    },
    rapidlyQuestionBadge: {
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    rapidlyQuestionTitle: {
      lineHeight: 22,
      marginBottom: 14,
    },
    rapidlyVideoWrapper: {
      marginTop: 14,
      borderRadius: 12,
      overflow: 'hidden',
    },
    rapidlyQuestionTitleText: {
      marginTop: 14,
      marginBottom: 6,
    },
    rapidlyTranscriptionSection: {
      marginTop: 12,
    },
    rapidlyTranscriptionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 10,
    },
    rapidlyTranscriptionContent: {
      marginTop: 4,
    },
    rapidlyTranscriptionText: {
      lineHeight: 22,
    },
    rapidlyWordWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    rapidlyWordHighlight: {
      paddingHorizontal: 2,
      borderRadius: 3,
    },
    rapidlyResponseHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.gray[100],
      marginBottom: 10,
    },
    rapidlyResponseLabel: {
      letterSpacing: 0.5,
    },
    rapidlyPlaySnippetBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: colors.brand[50],
    },
    rapidlyTranscriptionWrap: {
      marginBottom: 14,
    },
    rapidlyWordRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 2,
    },
    rapidlyWordText: {
      lineHeight: 22,
    },
    rapidlyWordActive: {
      backgroundColor: colors.brand[100],
      borderRadius: 4,
    },
    rapidlyCardFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.gray[100],
    },
    rapidlyCopyPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.gray[300],
      backgroundColor: colors.base.white,
    },
    topHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    breakdownButton: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: colors.brand[50],
      borderWidth: 1,
      borderColor: colors.brand[200],
    },
    questionDropdownTrigger: {
      borderWidth: 1,
      borderColor: colors.gray[300],
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: colors.base.white,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    dropdownOptionsList: {
      borderWidth: 1,
      borderColor: colors.gray[200],
      borderRadius: 8,
      backgroundColor: colors.base.white,
      marginBottom: 10,
      overflow: 'hidden',
    },
    dropdownOptionItem: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.gray[100],
    },
    dropdownOptionActive: {
      backgroundColor: colors.brand[50],
    },
    badgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 14,
    },
    pillBadge: {
      backgroundColor: colors.gray[100],
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
    },
    videoContainer: {
      borderRadius: 12,
      overflow: 'hidden',
      marginBottom: 16,
      backgroundColor: colors.gray[900],
      height: 220,
    },
    videoPlayerBox: {
      width: '100%',
      height: '100%',
    },
    questionHeader: {
      marginBottom: 12,
    },
    transcriptionSection: {
      marginTop: 12,
    },
    transcriptionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    toggleRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
    toggleButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.gray[300],
      backgroundColor: colors.base.white,
    },
    toggleButtonActive: {
      borderColor: colors.brand[600],
      backgroundColor: colors.brand[50],
    },
    continuousBox: {
      backgroundColor: colors.gray[50],
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.gray[200],
    },
    wordWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
    },
    wordHighlight: {
      backgroundColor: colors.brand[100],
      paddingHorizontal: 4,
      paddingVertical: 2,
      borderRadius: 4,
    },
    timelineRow: {
      flexDirection: 'row',
      gap: 12,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.gray[100],
    },
    timelineTimestamp: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: colors.brand[50],
      alignSelf: 'flex-start',
    },
    timelineContent: {
      flex: 1,
    },
    emptyStateContainer: {
      padding: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // Modal Styles
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalBackdrop: {
      flex: 1,
    },
    modalContainer: {
      backgroundColor: colors.base.white,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 24,
      maxHeight: '85%',
    },
    modalHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.gray[200],
    },
    modalScroll: {
      marginVertical: 12,
    },
    closeButton: {
      padding: 6,
    },
    introParagraph: {
      lineHeight: 20,
      marginBottom: 14,
    },
    sectionHeader: {
      letterSpacing: 0.5,
      marginTop: 10,
      marginBottom: 8,
    },
    criteriaList: {
      gap: 10,
      marginBottom: 14,
    },
    criteriaRow: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'flex-start',
    },
    criteriaIconWrap: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.brand[50],
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    criteriaContent: {
      flex: 1,
    },
    levelsList: {
      gap: 6,
      marginBottom: 14,
    },
    levelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.gray[50],
      borderRadius: 8,
      padding: 8,
    },
    levelBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      minWidth: 32,
      alignItems: 'center',
    },
    levelName: {
      flex: 1,
    },
    disclaimerText: {
      lineHeight: 16,
      marginTop: 8,
    },
    modalFooter: {
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.gray[200],
    },
    backButtonWrap: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.brand[600],
      borderRadius: 6,
      alignSelf: 'flex-start',
    },

    // Breakdown Modal Specific
    scoreHeroRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 12,
    },
    cefrBadgeLarge: {
      borderWidth: 1.5,
      borderColor: colors.success[500],
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.success[50],
    },
    scoreHeroInfo: {
      flex: 1,
    },
    rowAlignBaseline: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 4,
    },
    segmentedBar: {
      flexDirection: 'row',
      gap: 3,
      marginBottom: 14,
    },
    segment: {
      flex: 1,
      height: 8,
      borderRadius: 2,
    },
    summaryParagraph: {
      lineHeight: 20,
      marginBottom: 14,
    },
    skillCardsList: {
      gap: 8,
      marginBottom: 14,
    },
    skillCard: {
      backgroundColor: colors.gray[50],
      borderRadius: 10,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.gray[200],
    },
    skillCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 6,
    },
    skillLevelPill: {
      backgroundColor: colors.success[100],
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    skillDesc: {
      lineHeight: 16,
    },
    breakdownFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.gray[200],
    },
    howCalculatedButton: {
      paddingVertical: 4,
    },

    // Utilities
    flex1: {
      flex: 1,
    },
    marginTop2: {
      marginTop: 2,
    },
  });
