export const JOBS_ACTION_TYPES = {
  GET_PUBLISHED_JOBS_REQUEST: "jobs/GET_PUBLISHED_JOBS_REQUEST",
  GET_UNPUBLISHED_JOBS_REQUEST: "jobs/GET_UNPUBLISHED_JOBS_REQUEST",
  GET_JOBS_REQUEST: 'jobs/GET_JOBS_REQUEST',
  GET_JOBS_SUCCESS: 'jobs/GET_JOBS_SUCCESS',
  GET_JOBS_FAILURE: 'jobs/GET_JOBS_FAILURE',
  GET_JOB_DETAIL_REQUEST: 'jobs/GET_JOB_DETAIL_REQUEST',
  GET_JOB_DETAIL_SUCCESS: 'jobs/GET_JOB_DETAIL_SUCCESS',
  GET_JOB_DETAIL_FAILURE: 'jobs/GET_JOB_DETAIL_FAILURE',
  CREATE_JOB_REQUEST: 'jobs/CREATE_JOB_REQUEST',
  CREATE_JOB_SUCCESS: 'jobs/CREATE_JOB_SUCCESS',
  CREATE_JOB_FAILURE: 'jobs/CREATE_JOB_FAILURE',
  UPDATE_JOB_REQUEST: 'jobs/UPDATE_JOB_REQUEST',
  UPDATE_JOB_SUCCESS: 'jobs/UPDATE_JOB_SUCCESS',
  UPDATE_JOB_FAILURE: 'jobs/UPDATE_JOB_FAILURE',
  DELETE_JOB_REQUEST: 'jobs/DELETE_JOB_REQUEST',
  DELETE_JOB_SUCCESS: 'jobs/DELETE_JOB_SUCCESS',
  DELETE_JOB_FAILURE: 'jobs/DELETE_JOB_FAILURE',
  CLEAR_ERROR: 'jobs/CLEAR_ERROR',
  SET_SELECTED_JOB: 'jobs/SET_SELECTED_JOB',
  GET_JOB_NAME_LIST_REQUEST: "jobs/GET_JOB_NAME_LIST_REQUEST",
  GENERATE_JOB_DESCRIPTION_REQUEST: "jobs/GENERATE_JOB_DESCRIPTION_REQUEST",
  /** Wizard application form: POST or PATCH screening preferences + bulk criteria */
  SUBMIT_APPLICATION_FORM_STEP_REQUEST: "jobs/SUBMIT_APPLICATION_FORM_STEP_REQUEST",
  /** PATCH /job/v1/jobs/:id/ with `users_shared_with_ids` (team invite step). */
  PATCH_JOB_USERS_SHARED_REQUEST: "jobs/PATCH_JOB_USERS_SHARED_REQUEST",
  /** PATCH /job/v1/jobs/:id/ — save job details from wizard step 1. */
  PATCH_JOB_DETAILS_REQUEST: "jobs/PATCH_JOB_DETAILS_REQUEST",
  /** GET resume-screening-preferences + GET job criteria (application form step 2). */
  FETCH_APPLICATION_FORM_DRAFT_REQUEST: "jobs/FETCH_APPLICATION_FORM_DRAFT_REQUEST",
  /** PATCH /job/v1/jobs/:id/ with `{ published }` from jobs list overflow menu. */
  PATCH_JOB_PUBLISHED_REQUEST: "jobs/PATCH_JOB_PUBLISHED_REQUEST",
  /** PATCH /job/v1/jobs/:id/ with `{ is_deleted: true, deleted_by }`. */
  SOFT_DELETE_JOB_REQUEST: "jobs/SOFT_DELETE_JOB_REQUEST",
  /** POST /workflow/assign/:jobId/ — assign workflow + invite options. */
  ASSIGN_WORKFLOW_TO_JOB_REQUEST: "jobs/ASSIGN_WORKFLOW_TO_JOB_REQUEST",
} as const;

