/** Default `o` for GET /assessments/v1/filter — newest assignment first */
export const DEFAULT_ASSIGNED_ASSESSMENTS_ORDER = "-assigned_at" as const;

export const ASSESSMENTS_ACTION_TYPES = {
    GET_ASSESSMENTS_REQUEST: "assessments/GET_ASSESSMENTS_REQUEST",
    GET_ASSESSMENTS_SUCCESS: "assessments/GET_ASSESSMENTS_SUCCESS",
    GET_ASSESSMENTS_FAILURE: "assessments/GET_ASSESSMENTS_FAILURE",
    GET_ASSIGNED_ASSESSMENTS_REQUEST: "assessments/GET_ASSIGNED_ASSESSMENTS_REQUEST",
    GET_ASSIGNED_ASSESSMENTS_SUCCESS: "assessments/GET_ASSIGNED_ASSESSMENTS_SUCCESS",
    GET_ASSIGNED_ASSESSMENTS_FAILURE: "assessments/GET_ASSIGNED_ASSESSMENTS_FAILURE",
    FETCH_ASSESSMENT_OVERVIEW_REQUEST: "assessments/FETCH_ASSESSMENT_OVERVIEW_REQUEST",
    FETCH_BLUEPRINT_ASSIGNMENTS_LIST_REQUEST:
      "assessments/FETCH_BLUEPRINT_ASSIGNMENTS_LIST_REQUEST",
    EXPORT_BLUEPRINT_ASSIGNMENTS_REPORT_REQUEST:
      "assessments/EXPORT_BLUEPRINT_ASSIGNMENTS_REPORT_REQUEST",
  } as const;
  