export const ASSESSMENTS_ACTION_TYPES = {
    GET_ASSESSMENTS_REQUEST: "assessments/GET_ASSESSMENTS_REQUEST",
    GET_ASSESSMENTS_SUCCESS: "assessments/GET_ASSESSMENTS_SUCCESS",
    GET_ASSESSMENTS_FAILURE: "assessments/GET_ASSESSMENTS_FAILURE",
  } as const;
  